name: logistic_common
description: Logistic Common
version: 0.1.0
environment:
  sdk: '>=1.20.0 <2.0.0'
dependencies:
  dartson: "^0.2.5"
  intl: any
transformers:
- dartson
dev_dependencies:
  test: ^0.12.3
